export const GET_PRODUCTS_REQUEST = "GET_PRODUCTS_REQUEST";
export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const GET_PRODUCTS_FAIL = "GET_PRODUCTS_FAIL";

export const GET_PRODUCT_DETAILS_REQUEST = "GET_PRODUCT_DETAILS_REQUEST";
export const GET_PRODUCT_DETAILS_SUCCESS = "GET_PRODUCT_DETAILS_SUCCESS";
export const GET_PRODUCT_DETAILS_FAIL = "GET_PRODUCT_DETAILS_FAIL";

export const GET_PRODUCTS_BY_CATEGORY_REQUEST = "GET_PRODUCTS_BY_CATEGORY_REQUEST"
export const GET_PRODUCTS_BY_CATEGORY_SUCCESS = "GET_PRODUCTS_BY_CATEGORY_SUCCESS"
export const GET_PRODUCTS_BY_CATEGORY_RESPONSE_FAIL = "GET_PRODUCTS_BY_CATEGORY_RESPONSE_FAIL"

export const RATE_PRODUCT_REQUEST = "RATE_PRODUCT_REQUEST"
export const RATE_PRODUCT_SUCCESS = "RATE_PRODUCT_SUCCESS"
export const RATE_PRODUCT_FAIL = "RATE_PRODUCT_FAIL"

export const PRODUCT_UNMOUNT = "PRODUCT_UNMOUNT"

export const ADD_PRODUCT_TO_COMPARE = "ADD_PRODUCT_TO_COMPARE"